Repository OpenMined/pygrid-admin, pull requests merged in 2021-02, with the labels that each got.

#2 Migrate to Next.js
  .gitignore
  LICENSE
  README.md
  components/Header/index.js
  package.json
  pages/404.js
  pages/_app.js
  pages/api/hello.js
  pages/datasets/index.js
  pages/datasets/requests.js
  pages/datasets/tensors.js
  pages/finances/index.js
  pages/index.js
  pages/infrastructure/index.js
  pages/infrastructure/nodes.js
  pages/infrastructure/workers.js
  pages/models/index.js
  pages/settings/associations.js
  pages/settings/branding.js
  pages/settings/index.js
  pages/settings/infrastructure.js
  pages/settings/monetization.js
  pages/users/groups.js
  pages/users/index.js
  pages/users/roles.js
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/pygrid.png
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/components/Header/Header.js
  src/components/Header/index.js
  src/components/index.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/routes/Homepage.js
  src/routes/index.js
  src/setupTests.js
  styles/globals.css
  yarn.lock
Labels: Type: Refactor :hammer:

#9 Setup data fetching
  .env.development
  .env.local.example
  next-env.d.ts
  package.json
  src/contexts/axios-context.tsx
  src/hooks/axios.ts
  src/hooks/datasets.ts
  src/pages/_app.js
  src/pages/_app.tsx
  tsconfig.json
  yarn.lock
Labels: Type: New Feature :heavy_plus_sign:

#12 feat(dashboard): dashboard ui
  .eslintrc.js
  .prettierignore
  package.json
  src/components/Header/index.js
  src/components/icons/arrows.tsx
  src/components/icons/triangles.tsx
  src/components/pages/dashboard/card/_data.tsx
  src/components/pages/dashboard/card/index.tsx
  src/hooks/datasets.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/dashboard/index.tsx
  src/pages/index.js
  src/pages/index.tsx
  src/styles/globals.css
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: Type: New Feature :heavy_plus_sign:

#25 Testing framework setup
  .babelrc
  .eslintrc.js
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/app.spec.ts
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  jest.config.js
  package.json
  setupTests.js
  src/tests/index.test.jsx
  yarn.lock
Labels: Type: Testing :test_tube:

#29 feat: tentative datasets ui
  package.json
  src/components/icons/arrows.tsx
  src/components/icons/close.tsx
  src/components/icons/file.tsx
  src/components/icons/triangles.tsx
  src/components/lib.tsx
  src/components/pages/dashboard/card/index.tsx
  src/components/pages/datasets/cards/datasets.tsx
  src/components/pages/datasets/cards/requests.tsx
  src/components/pages/datasets/cards/tensors.tsx
  src/pages/datasets/[slug].tsx
  src/pages/datasets/index.js
  src/pages/datasets/index.tsx
  src/pages/datasets/requests.js
  src/pages/datasets/requests.tsx
  src/pages/datasets/tensors.js
  src/pages/datasets/tensors.tsx
  src/styles/globals.css
  tailwind.config.js
  yarn.lock
Labels: Status: Completed :heavy_check_mark:
