Repository OpenMined/pygrid-admin, pull requests merged in 2021-03, with the labels that each got.

#35 Users & Roles
  package.json
  src/components/pages/users/cards/groups.tsx
  src/components/pages/users/cards/roles.tsx
  src/components/pages/users/cards/users.tsx
  src/pages/api/users.ts
  src/pages/users/groups.js
  src/pages/users/groups.tsx
  src/pages/users/index.js
  src/pages/users/index.tsx
  src/pages/users/roles.js
  src/pages/users/roles.tsx
  src/types/api-responses.ts
  src/types/users.ts
  yarn.lock
Labels: Type: New Feature :heavy_plus_sign:

#41 User login and auth context
  .eslintignore
  .prettierignore
  jest.config.js
  package.json
  src/__tests__/index.test.js
  src/__tests__/pygrid-admin.test.js
  src/components/auth-route.tsx
  src/components/header/index.tsx
  src/components/icons/spinner.tsx
  src/components/pages/users/cards/roles.tsx
  src/context/auth-context.tsx
  src/context/index.tsx
  src/layouts/app.tsx
  src/layouts/blank.tsx
  src/lib/auth.ts
  src/lib/user.ts
  src/pages/_app.tsx
  src/pages/api/hello.js
  src/pages/index.tsx
  src/pages/login.tsx
  src/styles/globals.css
  src/utils/api-axios.ts
  tailwind.config.js
  yarn.lock
Labels: Status: Review Needed :raising_hand:

#52 Users Flow [Edit/Delete]
  .env.development
  .env.local.example
  package.json
  src/components/icons/marks.tsx
  src/components/lib.tsx
  src/components/modals/groups/create/index.tsx
  src/components/modals/groups/delete/index.tsx
  src/components/modals/groups/edit/index.tsx
  src/components/modals/modal.tsx
  src/components/modals/roles/create/index.tsx
  src/components/modals/roles/delete/index.tsx
  src/components/modals/roles/edit/index.tsx
  src/components/pages/users/cards/roles.tsx
  src/lib/user-permissions.ts
  src/lib/utils.ts
  src/pages/api/groups.ts
  src/pages/api/roles.ts
  src/pages/api/users.ts
  src/pages/datasets/[slug].tsx
  src/pages/users/groups/[slug].tsx
  src/pages/users/groups/index.tsx
  src/pages/users/index.tsx
  src/pages/users/roles.tsx
  src/pages/users/roles/[slug].tsx
  src/pages/users/roles/index.tsx
  src/styles/globals.css
  src/types/api-responses.ts
  src/types/users.ts
  yarn.lock
Labels: Type: New Feature :heavy_plus_sign:, Type: Refactor :hammer:

#50 Feature datasets/requests list
  src/components/icons/close.tsx
  src/components/icons/marks.tsx
  src/components/icons/search.tsx
  src/components/icons/user.tsx
  src/components/lib.tsx
  src/components/pages/datasets/cards/datasets.tsx
  src/components/pages/datasets/cards/requests.tsx
  src/components/pages/datasets/cards/tensors.tsx
  src/pages/api/datasets.ts
  src/pages/api/dcfl/datasets/index.ts
  src/pages/datasets/index.tsx
  src/pages/datasets/requests.tsx
  src/types/api-responses.ts
  src/types/datasets.ts
Labels: Status: Review Needed :raising_hand:, Type: Improvement :chart_with_upwards_trend:
